version: '3.7'

services:
  #地面服务器配置
  dst_server_master:
    image: jamesits/dst-server:nightly
    container_name: dst_server_master
    restart: always
    ports:
      - "10998:10998/udp"
      - "10999:10999/udp"
    volumes:
      - /home/ssdlh/dockers/dst/dst_config:/home/steam/dst_config
    environment:
      CLUSTER_NAME: dst_server   #服务器文件夹名
      WORLD_NAME: master         #世界显示名
      WORLD_TYPE: Master         #世界类型：地面
      STEAM_PORT: 10998
      MASTER_PORT: 10999

  #洞穴服务器配置
  dst_server_caves:
    image: jamesits/dst-server:nightly
    container_name: dst_server_caves
    restart: always
    ports:
      - "11000:11000/udp"
      - "11001:11001/udp"
    volumes:
      - /home/ssdlh/dockers/dst/dst_config:/home/steam/dst_config
    environment:
      CLUSTER_NAME: dst_server
      WORLD_NAME: caves
      WORLD_TYPE: Caves
      SHARD_MASTER_PORT: 10999


      LAN_ONLY: "true"
      # SERVER_PASSWORD: XXX设置连接密码
      # CLUSTER_TOKEN: "在这里粘贴您的Klei服务器令牌"
